### ISSUE TITLE
Handle overlong toots

### ISSUE THREAD

**Issue by nipafx** [kytta/toot#20]
(First of all, thanks for this project - very cool! ❤️ )

I just included this on my website and noticed that when sharing overlong toots, the server throws an error. [Try it with this text.](https://toot.kytta.dev/?text=This%20text%20has%20502%20characters%20-%20as%20is,%20pressing%20%22TOOT!%22%20leads%20to%20an%20error,%20but%20when%20deleting%20a%20few%20characters%20(sometimes%20up%20to%20100),%20it%20works.%20Lorem%20ipsum%20dolor%20sit%20amet,%20consetetur%20sadipscing%20elitr,%20sed%20diam%20nonumy%20eirmod%20tempor%20invidunt%20ut%20labore%20et%20dolore%20magna%20aliquyam%20erat,%20sed%20diam%20voluptua.%20At%20vero%20eos%20et%20accusam%20et%20justo%20duo%20dolores%20et%20ea%20rebum.%20Stet%20clita%20kasd%20gubergren,%20no%20sea%20takimata%20sanctus%20est%20Lorem%20ipsum%20dolor%20sit%20amet.%20Lorem%20ipsum%20dolor%20sit%20amet,%20consetetur%20sadipscing%20elitr,%20sedar.)

That said, it isn't simply "501 characters fail", "500 work" (which I kinda expected). Instead the working number of characters varies. Sometimes I had to go as low 430 for it to work, sometimes a few more were possible as well. 🤷🏾

**Comment by kytta** [comment]
I've tried it — and it seems to work just fine (albeit, some instances just do not allow toots longer than 500 characters)

<details>
<summary>Screenshots</summary>

![Screenshot of posting to FOSStodon](https://user-images.githubusercontent.com/6566248/175613578-2cbc85ec-ff8f-4bd3-9650-2c1e32688568.png)

![Screenshot of posting to mastodon.ml](https://user-images.githubusercontent.com/6566248/175613777-e5024e86-fe6c-454b-a653-12a9cf1fe98c.png)

![Screenshot of posting to norden.social](https://user-images.githubusercontent.com/6566248/175614028-7741bd3b-d854-420f-9adf-d5da40ec294e.png)

</details>

I guess I'll need more details. What is/are the instance(s) you've tried it with? It'd also be helpful if you tell me your browser and OS versions 🤔

**Comment by nipafx** [comment]
This happens with https://mastodon.technology/ (on Linux with Firefox 102.2 and Chrome 103.0.5060.53):

![image](https://user-images.githubusercontent.com/6537432/177035029-a24d9f5a-a1a9-4fd5-be27-94d50fa3c383.png)

So maybe it's an issue with their instance?

**Comment by kytta** [comment]
> This happens with [mastodon.technology](https://mastodon.technology/)

Hmm, I don’t have an account there; for me, it first redirects me to the index page.

Could you inspect the logs in the Network tab of your DevTools? Perhaps there are some extra metadata to this error.

> So maybe it’s an issue with their instance?

Could as well be that. @ashfurrow you seem to be the admin, do you perhaps have any information on this?

**Comment by ashfurrow** [comment]
Hi! I am the admin for mastodon.technology and I'll try to provide some help. m.t has a status length max of 512 instead of the standard 500, which is enabled by changing the two following lines of code.

On the backend:

https://github.com/ashfurrow/mastodon/blob/9fa31c739c1d71594e1088188556e7281f2ebad8/app/validators/status_length_validator.rb#L4

And on the frontend:

https://github.com/ashfurrow/mastodon/blob/9fa31c739c1d71594e1088188556e7281f2ebad8/app/javascript/mastodon/features/compose/components/compose_form.js#L93

I agree that the console messages would be helpful here. Let me know if I can provide more details on my end.

**Comment by nipafx** [comment]
Mastodon.technology is shutting down (thank you for your service, @ashfurrow 🫡) and I have not observed this issue elsewhere. I will hence close this issue.
