### ISSUE TITLE
Adding New Line charachter

### ISSUE THREAD

**Issue by mpaglia0** [kytta/toot#21]
Hi!
Seems I cannot split text in multiple lines...
Can you please help?
Thanks

**Comment by kytta** [comment]
Hello, could you provide a bit more information? What is the example text you are trying to post, and what is the toot's and Mastodon instance URL? Also, what browser and OS are you on?

I have tried it right now, and for me, it still works fine 🤔

**Comment by mpaglia0** [comment]
I am trying to use your service through a plugin written in Python.
I use the following string (example):
`f"https://toot.kytta.dev/?text={title}{LF}{url}{LF}{hashtags}"`
and - before this instruction - I defined
`LF = '\n'`

**Comment by mpaglia0** [comment]
Tested also the method
`import os`
and then
`f"https://toot.kytta.dev/?text={title}{os.linesep}{url}{os.linesep}{hashtags}"`
without success

**Comment by kytta** [comment]
> I use the following string (example):
> `f"https://toot.kytta.dev/?text={title}{LF}{url}{LF}{hashtags}"`
> and - before this instruction - I defined
> `LF = '\n'`

I think the problem is that your newline character is not URL encoded. For example, you can't put whitespaces in URLs, you have to replace them with `%20`. For a newline, that would be `%0D%0A`

I suggest you change your script a little bit as follows:

```py
from urllib.parse import urlencode

query = urlencode({
    "text": f"{title}{LF}{url}{LF}{hashtags}"
})

url = f"https://toot.kytta.dev/?{query}"
```

**Comment by kytta** [comment]
> Tested also the method
> `import os`
> and then
> `f"https://toot.kytta.dev/?text={title}{os.linesep}{url}{os.linesep}{hashtags}"`
> without success

And I wouldn't use `os.linesep` in this case. `os.linesep` is meant for files stored on different filesystems in different OSes: on Windows, it's CRLF, but on Unix-based OSes, it's LF. On the Web, however, it's the same everywhere, and you can just use `\n`

**Comment by mpaglia0** [comment]
Works perfectly!
The problem was actually my poor Python knowledge.
Please apologize...

**Comment by kytta** [comment]
No problem! Glad I could help you ☺️
